### PR TITLE
ignore empty string class name when building dataflow metadata

### PR DESCRIPTION
**Pull request by tinedel**
## Summary
Fixes issue #438
A lot of properties generated by configuration metadata do not have sourceType field set, which in turn matches the empty class name for the case when a list of classes has a trailing comma in the config file.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by anthonydahanne** [comment]
@kohlmu-pivotal are you ok with this change?

**Comment by anthonydahanne** [comment]
thanks @tinedel for your contribution!
I'm checking if that does indeed fix #438 

Also, we're in the middle of dual arch changes, let's wait for this to finish before we merge this one

**Comment by tinedel** [comment]
@anthonydahanne sure, no problem.

Please let me know when you are ready and I'll update my branch with the latest main

**Comment by kohlmu-pivotal** [comment]
> @kohlmu-pivotal are you ok with this change?

@anthonydahanne , yes I'm ok with this change. Ignore empty classes is what I would have done as well.

**Review by pivotal-david-osullivan — APPROVED** [review]

**Pull request merged**
